language: ruby
os: linux
sudo: false

gemfile:
  - gemfiles/Gemfile.td-agent-3.8.1
  - gemfiles/Gemfile.td-agent-4.0.1

# Test with supported td-agent versions
# https://tddocs.atlassian.net/wiki/spaces/PD/pages/6291635/The+td-agent+ChangeLog
# https://docs.fluentd.org/quickstart/td-agent-v2-vs-v3-vs-v4
matrix:
  include:
    - rvm: 2.7.2 # Latest supported Ruby (less than v3.0.0) / https://www.ruby-lang.org/en/downloads/
      gemfile: gemfiles/Gemfile.fluentd-1.12.0 # Latest Fluentd / https://www.fluentd.org/download
    - rvm: 2.3.0 # Oldest supported Ruby
      gemfile: gemfiles/Gemfile.fluentd-0.14.22 # Oldest supported Fluentd
    - rvm: 2.4.2 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.1.1/config/projects/td-agent3.rb#L17
      gemfile: gemfiles/Gemfile.td-agent-3.1.1
    - rvm: 2.4.4 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.2.1/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.2.1
    - rvm: 2.4.5 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.3.0/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.3.0
    - rvm: 2.4.6 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.4.1/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.4.1
    - rvm: 2.4.9 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.5.1/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.5.1
    - rvm: 2.4.9 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.6.0/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.6.0
    - rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.7.1/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.7.1
    - rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.8.0/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.8.0
    - rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/blob/master/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.8.1
    - rvm: 2.7.1 # https://github.com/fluent-plugins-nursery/td-agent-builder/blob/v4.0.1/td-agent/config.rb#L16
      gemfile: gemfiles/Gemfile.td-agent-4.0.1
      
  fast_finish: true

script: bundle exec rake test
